# Licensed under the MIT License. See LICENSE file in the project root for details.

version: 2

run:
  timeout: 5m
  go: "1.24"
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: false

linters-settings:
  # Security-focused linters
  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)
      - G601 # Implicit memory aliasing in for loop
    config:
      # Allow some specific patterns for performance-critical code
      G404:
        # Allow math/rand in performance-critical paths where crypto/rand is too slow
        - "internal/storage/index/.*"
        - "internal/core/.*"
      G601:
        # Allow implicit memory aliasing in specific performance-critical loops
        - "internal/storage/index/.*"
  
  # Code quality linters
  govet:
    settings:
      shadow:
        strict: false
  
  # Performance linters
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  # Style and formatting
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/kianostad/lfdb
  
  # Error handling
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions: fmt:.*
  
  # Unused code detection
  unused:
    check-exported: false
  
  # Dead code detection
  deadcode:
    check-generated: false
  
  # Complexity analysis
  cyclop:
    max-complexity: 15
    package-average: 10.0
    skip-tests: true
  
  # Function length
  funlen:
    lines: 100
    statements: 50
  
  # Line length
  lll:
    line-length: 120
    tab-width: 1
  
  # Naming conventions
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: package-comments
        disabled: true
      - name: var-naming
        arguments:
          - ID
          - API
          - ACL
          - ASCII
          - CPU
          - CSS
          - DNS
          - EOF
          - GUID
          - HTML
          - HTTP
          - HTTPS
          - ID
          - IP
          - JSON
          - QPS
          - RAM
          - RPC
          - SLA
          - SMTP
          - SQL
          - SSH
          - TCP
          - TLS
          - TTL
          - UDP
          - UI
          - GID
          - UID
          - UUID
          - URI
          - URL
          - UTF8
          - VM
          - XML
          - XMPP
          - XSRF
          - XSS
          - SIP
          - RTP
          - AMQP
          - DB
          - TS

linters:
  enable-all: true
  disable:
    - errcheck
    - ineffassign
    - staticcheck
issues:
  exclude-rules:
    # Exclude some rules for performance-critical code
    - path: internal/storage/index/
      linters:
        - gomnd
        - gocognit
        - cyclop
        - funlen
        - lll
        - goconst
        - dupl
        - gocritic
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - nakedret
        - noctx
        - nolintlint
        - predeclared
        - rowserrcheck
        - stylecheck
        - thelper
        - tparallel
        - unconvert
        - unparam
        - varcheck
        - wastedassign
        - whitespace
        - wrapcheck
        - wsl
        - godot
        - godox
        - goheader
    
    - path: internal/core/
      linters:
        - gomnd
        - gocognit
        - cyclop
        - funlen
        - lll
        - goconst
        - dupl
        - gocritic
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - nakedret
        - noctx
        - nolintlint
        - predeclared
        - rowserrcheck
        - stylecheck
        - thelper
        - tparallel
        - unconvert
        - unparam
        - varcheck
        - wastedassign
        - whitespace
        - wrapcheck
        - wsl
        - godot
        - godox
        - goheader
    
    - path: internal/concurrency/
      linters:
        - gomnd
        - gocognit
        - cyclop
        - funlen
        - lll
        - goconst
        - dupl
        - gocritic
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - nakedret
        - noctx
        - nolintlint
        - predeclared
        - rowserrcheck
        - stylecheck
        - thelper
        - tparallel
        - unconvert
        - unparam
        - varcheck
        - wastedassign
        - whitespace
        - wrapcheck
        - wsl
        - godot
        - godox
        - goheader
    
    - path: internal/monitoring/
      linters:
        - gomnd
        - gocognit
        - cyclop
        - funlen
        - lll
        - goconst
        - dupl
        - gocritic
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - nakedret
        - noctx
        - nolintlint
        - predeclared
        - rowserrcheck
        - stylecheck
        - thelper
        - tparallel
        - unconvert
        - unparam
        - varcheck
        - wastedassign
        - whitespace
        - wrapcheck
        - wsl
        - godot
        - godox
        - goheader
    
    - path: tests/
      linters:
        - gomnd
        - gocognit
        - cyclop
        - funlen
        - lll
        - goconst
        - dupl
        - gocritic
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - nakedret
        - noctx
        - nolintlint
        - predeclared
        - rowserrcheck
        - stylecheck
        - thelper
        - tparallel
        - unconvert
        - unparam
        - varcheck
        - wastedassign
        - whitespace
        - wrapcheck
        - wsl
        - godot
        - godox
        - goheader
    
    - path: cmd/
      linters:
        - gomnd
        - gocognit
        - cyclop
        - funlen
        - lll
        - goconst
        - dupl
        - gocritic
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - nakedret
        - noctx
        - nolintlint
        - predeclared
        - rowserrcheck
        - stylecheck
        - thelper
        - tparallel
        - unconvert
        - unparam
        - varcheck
        - wastedassign
        - whitespace
        - wrapcheck
        - wsl
        - godot
        - godox
        - goheader
    
    - path: examples/
      linters:
        - gomnd
        - gocognit
        - cyclop
        - funlen
        - lll
        - goconst
        - dupl
        - gocritic
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - nakedret
        - noctx
        - nolintlint
        - predeclared
        - rowserrcheck
        - stylecheck
        - thelper
        - tparallel
        - unconvert
        - unparam
        - varcheck
        - wastedassign
        - whitespace
        - wrapcheck
        - wsl
        - godot
        - godox
        - goheader

  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  fix: false
