# Licensed under the MIT License. See LICENSE file in the project root for details.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.2
    hooks:
      - id: golangci-lint
        args: [--timeout=5m]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet
      - id: go-build
      - id: go-test
      - id: go-test-race
      - id: go-cyclo
        args: [--over=15]
      - id: go-deadcode
      - id: go-unused
      - id: go-errcheck
      - id: go-gosec
      - id: go-staticcheck
      - id: go-misspell
      - id: go-govet
      - id: go-ineffassign
      - id: go-unconvert
      - id: go-varcheck
      - id: go-structcheck
      - id: go-typecheck
      - id: go-goconst
      - id: go-gocyclo
      - id: go-dupl
      - id: go-funlen
      - id: go-gocognit
      - id: go-gocritic
      - id: go-gomnd
      - id: go-gomodguard
      - id: go-goprintffuncname
      - id: go-gosimple
      - id: go-lll
      - id: go-nakedret
      - id: go-noctx
      - id: go-nolintlint
      - id: go-prealloc
      - id: go-predeclared
      - id: go-revive
      - id: go-rowserrcheck
      - id: go-stylecheck
      - id: go-thelper
      - id: go-tparallel
      - id: go-unparam
      - id: go-wastedassign
      - id: go-whitespace
      - id: go-wrapcheck
      - id: go-wsl
      - id: go-godot
      - id: go-godox
      - id: go-goheader
